#ifndef PROTOBETTER_DYNAMIC_LIB_GLOBAL_H
#define PROTOBETTER_DYNAMIC_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROTOBETTER_DYNAMIC_LIB_LIBRARY)
#  define PROTOBETTER_DYNAMIC_LIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROTOBETTER_DYNAMIC_LIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROTOBETTER_DYNAMIC_LIB_GLOBAL_H
